/**
 * Created by wangxiaoshuo on 2017/1/23.
 */
module.exports = {
    comment:{

    },
    user:{
        name:{type:String,required:true},
        password:{type:String,required:true},
        phone:Number,
        mail:String,
        birthday:String,
        signature:String,
        favourite:String
    },
    movie:{
        _id:Number,
        doctor:String,
        actor:String,
        name:String,
        country:String,
        summary:String,
        playCount:Number,
        score:Number,
        poster:String,
        maxPoster:String,
        minPoster:String,
        playUrl:String,
        year:Number,
        date:Number,
        kind:String,
        k:String,
        commentCount:Number
    },
    tv:{
        _id:Number,
        doctor:String,
        actor:String,
        name:String,
        country:String,
        summary:String,
        playCount:Number,
        score:Number,
        poster:String,
        maxPoster:String,
        minPoster:String,
        playUrl:String,
        year:Number,
        date:Number,
        kind:String,
        k:String,
        commentCount:Number,
        content:Object
    },
    ac:{
        _id:Number,
        doctor:String,
        actor:String,
        name:String,
        country:String,
        summary:String,
        playCount:Number,
        score:Number,
        poster:String,
        maxPoster:String,
        minPoster:String,
        playUrl:String,
        year:Number,
        date:Number,
        kind:String,
        k:String,
        commentCount:Number,
        content:Object
    },
    gm:{
        _id:Number,
        doctor:String,
        playTime:String,
        name:String,
        playCount:Number,
        poster:String,
        maxPoster:String,
        minPoster:String,
        playUrl:String,
        date:Number,
        kind:String,
        k:String,
        content:Object
    },
    dc:{
        _id:Number,
        doctor:String,
        playTime:String,
        name:String,
        playCount:Number,
        poster:String,
        maxPoster:String,
        minPoster:String,
        playUrl:String,
        date:Number,
        kind:String,
        k:String,
        content:Object
    },

    poster:{
        _id:Number,
        posterName:String,
        posterUrl:String,
        minPosterUrl:String
    }
};

